services:
  bot:
    build: .
    container_name: taxi-bot
    command: python bot.py
    env_file:
      - .env
    restart: unless-stopped

  userbot:
    build: .
    container_name: taxi-userbot
    command: python userbot.py
    env_file:
      - .env
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    restart: unless-stopped
